[display_name]
ru = "T-shape"

[levels.1_команда]
skills = [
    "понимание_sdlc_в_рамках_своего_п",
    "понимание_проблем_и_целей_каждой",
    "знание_смежных_зон_ответственнос",
]

[levels.2_компания]
skills = [
    "широкая_техническая_экспертиза_в",
    "глубокая_техническая_экспертиза",
    "владение_бизнесовой_частью",
    "глубокое_понимание_бизнеса_одной",
]
