[display_name]
ru = "Взаимодействие с бизнесом"

[levels.1_team]
skills = [
    "умение_продавать_идеи_бизнесу",
    "может_разработать_mvp",
]

[levels.2_company]
skills = [
    "бизнес_метрики",
    "okr",
    "юнит_экономика",
    "продуктовое_мышление",
]
