[display_name]
ru = "Лидерство"

[levels.1_team]
skills = [
    "организаторские_способности",
    "понимание_проблем_и_целей_бизнес",
    "умение_преподавать_наставничест",
    "инициативность",
    "эмоциональный_интеллект",
    "конфликт_менеджмент",
    "ответственность",
    "принятие_решений",
    "умение_взаимодействовать_с_други",
]

[levels.2_company]
skills = [
    "визионерство",
    "навык_знакомиться_с_зарубежным_о",
    "митапы",
    "нетворкинг",
    "фасилитация",
]

[levels.4_industry]
skills = [
    "евангелизм",
    "выступление_на_event",
]
