[display_name]
ru = "Навыки мышления"

[levels.1_команда]
skills = [
    "критическое_мышление",
]

[levels.2_компания]
skills = [
    "системное_мышление",
]

[levels.3_компания_несколько_средних_ко]
skills = [
    "триз",
    "дизайн_мышление",
    "мыслительные_инструменты_toc",
]
