[display_name]
ru = "Навыки мышления"

[levels.1_team]
skills = [
    "критическое_мышление",
]

[levels.2_company]
skills = [
    "системное_мышление",
]

[levels.3_several_companies]
skills = [
    "триз",
    "дизайн_мышление",
    "мыслительные_инструменты_toc",
]
