[display_name]
ru = "Процессные практики"

[levels.1_team]
skills = [
    "понимание_и_уверенное_использова",
    "scrum",
    "xp",
    "3_амиго",
    "team_kanban_practitioner",
]

[levels.2_company]
skills = [
    "safe",
    "практики_взаимодействия_с_другим",
    "devops",
    "devsecops",
    "less",
    "itil",
    "lean_startup",
    "disciplined_agile_delivery",
]

[levels.3_several_companies]
skills = [
    "beyond_budgeting",
    "management_30",
    "toc",
    "проектный_менеджмент_pmbok",
]
