[display_name]
ru = "Работа с данными"

[levels.1_команда]
skills = [
    "sqlnosql_знание_технолигии",
    "проектирование_бд",
    "оптимизация_запросов",
    "olap",
    "bigdata_если_проект_этой_темати",
    "оптимизация_сервера_бд",
]

[levels.2_компания]
skills = [
    "выбор_субд",
    "политики_backups",
    "stream_systems",
    "realtime_systems",
]

[levels.3_компания_несколько_средних_ко]
skills = [
    "dwh",
]
