[display_name]
ru = "Работа с данными"

[levels.1_team]
skills = [
    "sqlnosql_знание_технолигии",
    "проектирование_бд",
    "оптимизация_запросов",
    "olap",
    "bigdata_если_проект_этой_темати",
    "оптимизация_сервера_бд",
]

[levels.2_company]
skills = [
    "выбор_субд",
    "политики_backups",
    "stream_systems",
    "realtime_systems",
]

[levels.3_several_companies]
skills = [
    "dwh",
]
