[display_name]
ru = "Управление технологической стратегией"

[levels.1_team]
skills = [
    "roadmap_развития_технологий",
    "выбор_технологий_в_рамках_tech_r",
    "выбор_инженерных_практик_внед",
    "выбор_инструментов_поддержки_пра",
]

[levels.2_company]
skills = [
    "выбор_инженерных_практик",
    "выбор_инструментов_поддержки_пра",
    "формирование_tech_radar",
    "выбор_технологий_для_компании",
    "управление_процессом_переезда_на",
]

[levels.3_several_companies]
skills = [
    "евангилирование_практикинструме",
]

[levels.4_industry]
skills = [
    "создание_инструментов",
    "создание_практик",
]
