[display_name]
ru = "SOLID"

[links]
ru = "https://en.wikipedia.org/wiki/SOLID"

[descriptions]
ru = """
Мнемонический акроним, введённый Майклом Фэзерсом (Michael Feathers) для первых пяти принципов, названных Робертом Мартином в начале 2000-х, которые означали 5 основных принципов объектно-ориентированного программирования и проектирования.
"""