categories = [
    "навыки_мышления",
    "работа_с_данными",
    "архитектура",
    "практики_разработки",
    "практики_delivery",
    "инфраструктура",
    "работа_с_качеством",
    "работа_со_знаниями_knowledge_ma",
    "процессные_практики",
    "лидерство",
    "взаимодействие_с_бизнесом",
    "t_shape",
    "управление_технологической_страт",
]

levels = [
    '1_team',
    '2_company',
    '3_several_companies',
    '4_industry',
]

[display_name]
ru = "Модель зрелости техлида"
