[display_name]
ru = "Матрица зрелости"

categories = [
    "навыки_мышления",
    "работа_с_данными",
    "архитектура",
    "практики_разработки",
    "практики_delivery",
    "инфраструктура",
    "работа_с_качеством",
    "работа_со_знаниями_knowledge_ma",
    "процессные_практики",
    "лидерство",
    "взаимодействие_с_бизнесом",
    "t_shape",
    "управление_технологической_страт",
]
